// ignore_for_file: avoid_print
// Catalog generator: short, fun, relationship Q&A with unique short answers.
// Run: dart run tools/generate_relationship_catalog.dart

import 'dart:io';

void main() {
  final entries = _entries();
  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED — do not edit by hand. Run: dart run tools/generate_relationship_catalog.dart',
    )
    ..writeln(
      "import 'package:mevora/features/relationship/data/catalog/relationship_answer_builders.dart';",
    )
    ..writeln(
      "import 'package:mevora/features/relationship/data/catalog/relationship_questions.dart';",
    )
    ..writeln()
    ..writeln('List<RelationshipQuestion> buildRelationshipCatalogQuestions() {')
    ..writeln('  return [');
  for (final e in entries) {
    buffer.writeln('    relationshipQuestion(');
    buffer.writeln('      ${e.n},');
    buffer.writeln('      RelationshipTopic.${e.topic},');
    buffer.writeln("      r'''${e.en.replaceAll("'", r"\'")}''',");
    buffer.writeln("      r'''${e.tr.replaceAll("'", r"\'")}''',");
    buffer.writeln('      RelationshipQuestionType.choice,');
    buffer.writeln('      ${e.answersExpr},');
    buffer.writeln(
      '      category: RelationshipContentCategory.${e.category},',
    );
    buffer.writeln('    ),');
  }
  buffer.writeln('  ];');
  buffer.writeln('}');
  File('lib/features/relationship/data/catalog/relationship_catalog_entries.dart')
      .writeAsStringSync(buffer.toString());
  print('Wrote ${entries.length} questions');
}

class _Entry {
  _Entry({
    required this.n,
    required this.topic,
    required this.category,
    required this.en,
    required this.tr,
    required this.answersExpr,
  });
  final int n;
  final String topic;
  final String category;
  final String en;
  final String tr;
  final String answersExpr;
}

String _c({
  required String aEn,
  required String aTr,
  required String aV,
  required String bEn,
  required String bTr,
  required String bV,
  required String cEn,
  required String cTr,
  required String cV,
}) {
  String q(String s) => s.replaceAll("'", r"\'");
  return '''choiceAnswers(
        aEn: '${q(aEn)}',
        aTr: '${q(aTr)}',
        aValue: '${q(aV)}',
        bEn: '${q(bEn)}',
        bTr: '${q(bTr)}',
        bValue: '${q(bV)}',
        cEn: '${q(cEn)}',
        cTr: '${q(cTr)}',
        cValue: '${q(cV)}',
      )''';
}

List<_Entry> _entries() {
  final raw = <(String, String, String, String, String)>[
    // Interleaved: relationship / fun / daily / personality / lifestyle
    // topic used for matching badges; category for variety.
    (
      'flirting',
      'relationship',
      'Coffee or dinner for a first date?',
      'İlk buluşmada kahve mi, yemek mi?',
      _c(
        aEn: 'Coffee',
        aTr: 'Kahve',
        aV: 'coffee',
        bEn: 'Dinner',
        bTr: 'Yemek',
        bV: 'dinner',
        cEn: 'A walk',
        cTr: 'Yürüyüş',
        cV: 'walk',
      ),
    ),
    (
      'flirting',
      'fun',
      'Would you save your partner in a zombie apocalypse?',
      'Zombi istilasında sevgilini kurtarır mısın?',
      _c(
        aEn: 'Obviously yes',
        aTr: 'Tabii ki evet',
        aV: 'yes',
        bEn: 'Only if they run',
        bTr: 'Koşabilirse evet',
        bV: 'conditional',
        cEn: 'I run first',
        cTr: 'Önce ben kaçarım',
        cV: 'no',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Morning person or night owl?',
      'Sabah insanı mısın, gece insanı mı?',
      _c(
        aEn: 'Morning',
        aTr: 'Sabah',
        aV: 'morning',
        bEn: 'Night',
        bTr: 'Gece',
        bV: 'night',
        cEn: 'Depends on the day',
        cTr: 'Güne göre değişir',
        cV: 'flexible',
      ),
    ),
    (
      'communication',
      'relationship',
      'Who should text first?',
      'İlk mesajı kim atmalı?',
      _c(
        aEn: 'Whoever likes more',
        aTr: 'Daha ilgili olan',
        aV: 'interested',
        bEn: 'Either is fine',
        bTr: 'Fark etmez',
        bV: 'either',
        cEn: 'The other person',
        cTr: 'Karşı taraf',
        cV: 'other',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Can your partner take the last fry without asking?',
      'Sevgilin yemeğinden son patatesi izinsiz alabilir mi?',
      _c(
        aEn: 'Never',
        aTr: 'Asla',
        aV: 'never',
        bEn: 'Ask first',
        bTr: 'Önce sorsun',
        bV: 'ask',
        cEn: 'Share everything',
        cTr: 'Her şey ortak',
        cV: 'share',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Tea or coffee?',
      'Çay mı kahve mi?',
      _c(
        aEn: 'Tea',
        aTr: 'Çay',
        aV: 'tea',
        bEn: 'Coffee',
        bTr: 'Kahve',
        bV: 'coffee',
        cEn: 'Both',
        cTr: 'İkisi de',
        cV: 'both',
      ),
    ),
    (
      'communication',
      'relationship',
      'Do you need constant texting in a relationship?',
      'İlişkide sürekli mesajlaşmak gerekli mi?',
      _c(
        aEn: 'Yes, regularly',
        aTr: 'Evet, düzenli olsun',
        aV: 'yes',
        bEn: 'A few check-ins',
        bTr: 'Birkaç check-in yeter',
        bV: 'moderate',
        cEn: 'Not really',
        cTr: 'Gerekmez',
        cV: 'no',
      ),
    ),
    (
      'friendship',
      'fun',
      'If you get lost together, who opens the map?',
      'Birlikte kaybolsanız haritayı kim açar?',
      _c(
        aEn: 'I open it',
        aTr: 'Ben açarım',
        aV: 'me',
        bEn: 'My partner',
        bTr: 'Sevgilim',
        bV: 'partner',
        cEn: 'Ask a stranger',
        cTr: 'Birine sorarız',
        cV: 'ask',
      ),
    ),
    (
      'socialLife',
      'dailyLife',
      'Sea or mountains?',
      'Deniz mi dağ mı?',
      _c(
        aEn: 'Sea',
        aTr: 'Deniz',
        aV: 'sea',
        bEn: 'Mountains',
        bTr: 'Dağ',
        bV: 'mountains',
        cEn: 'Both seasons',
        cTr: 'İkisini de severim',
        cV: 'both',
      ),
    ),
    (
      'expectations',
      'relationship',
      'Should couples share everything?',
      'Sevgiliyle her şeyi paylaşmak gerekir mi?',
      _c(
        aEn: 'Almost everything',
        aTr: 'Neredeyse her şey',
        aV: 'almost_all',
        bEn: 'Important things',
        bTr: 'Önemli olanlar',
        bV: 'important',
        cEn: 'Keep some privacy',
        cTr: 'Biraz mahremiyet kalsın',
        cV: 'privacy',
      ),
    ),
    (
      'jealousy',
      'fun',
      'Would you wait if they say “getting ready” for 3 hours?',
      'Sevgilin 3 saat “hazırlanıyorum” derse bekler misin?',
      _c(
        aEn: 'Yes, patiently',
        aTr: 'Evet, sabırla',
        aV: 'yes',
        bEn: 'One reminder then go',
        bTr: 'Bir hatırlatırım',
        bV: 'nudge',
        cEn: 'I leave',
        cTr: 'Çıkarım',
        cV: 'leave',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Movie night in or night out?',
      'Evde film mi, dışarıda eğlence mi?',
      _c(
        aEn: 'Movie at home',
        aTr: 'Evde film',
        aV: 'home',
        bEn: 'Night out',
        bTr: 'Dışarı',
        bV: 'out',
        cEn: 'Mix it up',
        cTr: 'Karışık olsun',
        cV: 'mix',
      ),
    ),
    (
      'jealousy',
      'relationship',
      'Is a little jealousy cute?',
      'İlişkide kıskançlık biraz tatlı mıdır?',
      _c(
        aEn: 'A little is cute',
        aTr: 'Birazı tatlı',
        aV: 'a_little',
        bEn: 'Not really',
        bTr: 'Pek değil',
        bV: 'no',
        cEn: 'Depends how it’s shown',
        cTr: 'Nasıl gösterildiğine bağlı',
        cV: 'depends',
      ),
    ),
    (
      'money',
      'fun',
      'Bigger betrayal: finishing their fries?',
      'Hangisi daha büyük ihanet: patatesini bitirmek mi?',
      _c(
        aEn: 'Fries are sacred',
        aTr: 'Patates kutsaldır',
        aV: 'fries',
        bEn: 'Spoiling a show',
        bTr: 'Diziyi spoilerlamak',
        bV: 'spoiler',
        cEn: 'Both are crimes',
        cTr: 'İkisi de suç',
        cV: 'both',
      ),
    ),
    (
      'expectations',
      'personality',
      'Planned life or spontaneous?',
      'Planlı yaşamak mı, spontane olmak mı?',
      _c(
        aEn: 'Planned',
        aTr: 'Planlı',
        aV: 'planned',
        bEn: 'Spontaneous',
        bTr: 'Spontane',
        bV: 'spontaneous',
        cEn: 'A bit of both',
        cTr: 'İkisinden biraz',
        cV: 'mix',
      ),
    ),
    (
      'money',
      'relationship',
      'Who pays on a first date?',
      'İlk buluşmada hesap nasıl ödenmeli?',
      _c(
        aEn: 'Split',
        aTr: 'Paylaşarak',
        aV: 'split',
        bEn: 'Whoever invited',
        bTr: 'Davet eden',
        bV: 'inviter',
        cEn: 'Whoever offers',
        cTr: 'Teklif eden',
        cV: 'offer',
      ),
    ),
    (
      'socialLife',
      'fun',
      'If they watch the finale before you?',
      'Sevgilin dizinin son bölümünü senden önce izlerse?',
      _c(
        aEn: 'Unforgivable',
        aTr: 'Affedilmez',
        aV: 'unforgivable',
        bEn: 'Mildly annoyed',
        bTr: 'Biraz alınırım',
        bV: 'annoyed',
        cEn: 'No big deal',
        cTr: 'Önemli değil',
        cV: 'fine',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Cat or dog?',
      'Kedi mi köpek mi?',
      _c(
        aEn: 'Cat',
        aTr: 'Kedi',
        aV: 'cat',
        bEn: 'Dog',
        bTr: 'Köpek',
        bV: 'dog',
        cEn: 'Neither / both',
        cTr: 'İkisi / hiçbiri',
        cV: 'other',
      ),
    ),
    (
      'socialLife',
      'relationship',
      'Movie night or going out together?',
      'Birlikte film mi, dışarı çıkmak mı?',
      _c(
        aEn: 'Movie',
        aTr: 'Film',
        aV: 'movie',
        bEn: 'Going out',
        bTr: 'Dışarı',
        bV: 'out',
        cEn: 'Alternate',
        cTr: 'Nöbetleşe',
        cV: 'alternate',
      ),
    ),
    (
      'flirting',
      'fun',
      'Is an IKEA trip a relationship test?',
      'Birlikte IKEA’ya gitmek ilişki testi midir?',
      _c(
        aEn: 'Absolutely',
        aTr: 'Kesinlikle',
        aV: 'yes',
        bEn: 'Only if hungry',
        bTr: 'Açken gidersek',
        bV: 'hungry',
        cEn: 'Just shopping',
        cTr: 'Sadece alışveriş',
        cV: 'no',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Summer or winter?',
      'Yaz mı kış mı?',
      _c(
        aEn: 'Summer',
        aTr: 'Yaz',
        aV: 'summer',
        bEn: 'Winter',
        bTr: 'Kış',
        bV: 'winter',
        cEn: 'Spring / fall',
        cTr: 'İlkbahar / sonbahar',
        cV: 'mild',
      ),
    ),
    (
      'expectations',
      'relationship',
      'Same music taste with your partner?',
      'Sevgilinle aynı müzik zevkine sahip olmak önemli mi?',
      _c(
        aEn: 'Pretty important',
        aTr: 'Oldukça önemli',
        aV: 'important',
        bEn: 'Nice but optional',
        bTr: 'Güzel ama şart değil',
        bV: 'optional',
        cEn: 'Doesn’t matter',
        cTr: 'Önemli değil',
        cV: 'no',
      ),
    ),
    (
      'boundaries',
      'fun',
      'What if they snore?',
      'Sevgilin horluyorsa ne yaparsın?',
      _c(
        aEn: 'Earplugs forever',
        aTr: 'Kulak tıkacı',
        aV: 'earplugs',
        bEn: 'Gently wake them',
        bTr: 'Nazikçe uyandırırım',
        bV: 'wake',
        cEn: 'Separate rooms sometimes',
        cTr: 'Bazen ayrı oda',
        cV: 'space',
      ),
    ),
    (
      'money',
      'lifestyle',
      'Pizza or burger?',
      'Pizza mı hamburger mi?',
      _c(
        aEn: 'Pizza',
        aTr: 'Pizza',
        aV: 'pizza',
        bEn: 'Burger',
        bTr: 'Hamburger',
        bV: 'burger',
        cEn: 'Depends on the craving',
        cTr: 'Canına göre',
        cV: 'depends',
      ),
    ),
    (
      'flirting',
      'relationship',
      'Do you love surprises in a relationship?',
      'İlişkide sürprizleri sever misin?',
      _c(
        aEn: 'Love them',
        aTr: 'Çok severim',
        aV: 'love',
        bEn: 'Small ones only',
        bTr: 'Sadece küçükleri',
        bV: 'small',
        cEn: 'Prefer plans',
        cTr: 'Planı tercih ederim',
        cV: 'plans',
      ),
    ),
    (
      'exes',
      'fun',
      'They say an ex’s name by mistake?',
      'Sevgilin yanlışlıkla eski sevgilisinin adını söylerse?',
      _c(
        aEn: 'Big talk needed',
        aTr: 'Ciddi konuşuruz',
        aV: 'serious',
        bEn: 'Awkward but ok',
        bTr: 'Garip ama olur',
        bV: 'awkward',
        cEn: 'I laugh it off',
        cTr: 'Güler geçerim',
        cV: 'laugh',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Sweet or savory?',
      'Tatlı mı tuzlu mu?',
      _c(
        aEn: 'Sweet',
        aTr: 'Tatlı',
        aV: 'sweet',
        bEn: 'Savory',
        bTr: 'Tuzlu',
        bV: 'savory',
        cEn: 'Both moods',
        cTr: 'İki ruh hali',
        cV: 'both',
      ),
    ),
    (
      'futurePlans',
      'relationship',
      'Same city as your partner?',
      'Sevgilinle aynı şehirde yaşamak önemli mi?',
      _c(
        aEn: 'Very important',
        aTr: 'Çok önemli',
        aV: 'important',
        bEn: 'Long distance ok short-term',
        bTr: 'Kısa süre uzak olur',
        bV: 'short_ld',
        cEn: 'Distance is fine',
        cTr: 'Mesafe sorun değil',
        cV: 'distance_ok',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Desert island: what matters most to bring?',
      'Bir adaya düşseniz yanına ne almak istersin?',
      _c(
        aEn: 'Partner + snacks',
        aTr: 'Sevgili + atıştırmalık',
        aV: 'partner_food',
        bEn: 'Tools and water',
        bTr: 'Alet ve su',
        bV: 'survival',
        cEn: 'Phone and playlist',
        cTr: 'Telefon ve playlist',
        cV: 'phone',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Stay in or go out?',
      'Evde takılmak mı dışarı çıkmak mı?',
      _c(
        aEn: 'Stay in',
        aTr: 'Evde',
        aV: 'in',
        bEn: 'Go out',
        bTr: 'Dışarı',
        bV: 'out',
        cEn: '50/50',
        cTr: 'Yarı yarıya',
        cV: 'half',
      ),
    ),
    (
      'flirting',
      'relationship',
      'Is a hug ok on a first date?',
      'İlk buluşmada sarılmak normal mi?',
      _c(
        aEn: 'Yes if it feels right',
        aTr: 'Doğalsa evet',
        aV: 'yes',
        bEn: 'Maybe goodbye hug',
        bTr: 'Belki veda sarılması',
        bV: 'goodbye',
        cEn: 'Too soon',
        cTr: 'Erken',
        cV: 'no',
      ),
    ),
    (
      'money',
      'fun',
      'They eat your last pizza slice?',
      'Sevgilin senin son pizzanı yerse?',
      _c(
        aEn: 'War',
        aTr: 'Savaş',
        aV: 'war',
        bEn: 'They owe me one',
        bTr: 'Bana borçlu',
        bV: 'owe',
        cEn: 'I share anyway',
        cTr: 'Yine de paylaşırım',
        cV: 'share',
      ),
    ),
    (
      'communication',
      'dailyLife',
      'Texting or phone calls?',
      'Mesajlaşmak mı telefonda konuşmak mı?',
      _c(
        aEn: 'Texting',
        aTr: 'Mesaj',
        aV: 'text',
        bEn: 'Calls',
        bTr: 'Telefon',
        bV: 'call',
        cEn: 'Voice notes',
        cTr: 'Sesli mesaj',
        cV: 'voice',
      ),
    ),
    (
      'expectations',
      'relationship',
      'What matters most in a relationship?',
      'Bir ilişkide en önemli şey nedir?',
      _c(
        aEn: 'Trust',
        aTr: 'Güven',
        aV: 'trust',
        bEn: 'Fun together',
        bTr: 'Birlikte eğlenmek',
        bV: 'fun',
        cEn: 'Communication',
        cTr: 'İletişim',
        cV: 'communication',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Karaoke with your partner?',
      'Birlikte karaoke yapar mısın?',
      _c(
        aEn: 'Always',
        aTr: 'Her zaman',
        aV: 'always',
        bEn: 'After two songs warm-up',
        bTr: 'Isındiktan sonra',
        bV: 'warm_up',
        cEn: 'I’d rather listen',
        cTr: 'Dinlemeyi tercih ederim',
        cV: 'listen',
      ),
    ),
    (
      'expectations',
      'personality',
      'Quiet nights or busy calendars?',
      'Sakin akşamlar mı, dolu takvim mi?',
      _c(
        aEn: 'Quiet nights',
        aTr: 'Sakin akşamlar',
        aV: 'quiet',
        bEn: 'Busy social life',
        bTr: 'Dolu sosyal hayat',
        bV: 'busy',
        cEn: 'Seasonal mix',
        cTr: 'Mevsime göre',
        cV: 'mix',
      ),
    ),
    (
      'friendship',
      'relationship',
      'Want your partner to be your best friend too?',
      'Sevgilinle en iyi arkadaş olmak ister misin?',
      _c(
        aEn: 'Yes, best friends',
        aTr: 'Evet, en iyi arkadaş',
        aV: 'yes',
        bEn: 'Partner + other friends',
        bTr: 'Sevgili + başka arkadaşlar',
        bV: 'balanced',
        cEn: 'Romance first',
        cTr: 'Önce romantizm',
        cV: 'romance',
      ),
    ),
    (
      'expectations',
      'fun',
      'They hate your favorite song?',
      'Sevgilin senin favori şarkını sevmiyorsa?',
      _c(
        aEn: 'Dealbreaker playlist',
        aTr: 'Playlist kırılır',
        aV: 'dealbreaker',
        bEn: 'Headphones forever',
        bTr: 'Kulaklık sonsuza',
        bV: 'headphones',
        cEn: 'We joke about it',
        cTr: 'Şaka yaparız',
        cV: 'joke',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'What movie vibe would you pick together?',
      'Birlikte film izleyecek olsanız ne açardın?',
      _c(
        aEn: 'Comedy',
        aTr: 'Komedi',
        aV: 'comedy',
        bEn: 'Thriller',
        bTr: 'Gerilim',
        bV: 'thriller',
        cEn: 'Romance',
        cTr: 'Romantik',
        cV: 'romance',
      ),
    ),
    (
      'communication',
      'relationship',
      'Is slow texting a problem?',
      'Mesajlara geç cevap vermek sorun mu?',
      _c(
        aEn: 'Yes if often',
        aTr: 'Sık olursa evet',
        aV: 'often_yes',
        bEn: 'Busy is fine',
        bTr: 'Meşgulse sorun değil',
        bV: 'busy_ok',
        cEn: 'I don’t mind',
        cTr: 'Umursamam',
        cV: 'no',
      ),
    ),
    (
      'flirting',
      'fun',
      'You pocket-dial your mom on a first date?',
      'İlk buluşmada yanlışlıkla anneni ararsan?',
      _c(
        aEn: 'Hang up instantly',
        aTr: 'Hemen kapatırım',
        aV: 'hang_up',
        bEn: 'Own the awkward',
        bTr: 'Garibanlığı kabul ederim',
        bV: 'own_it',
        cEn: 'Introduce them briefly',
        cTr: 'Kısaca tanıştırırım',
        cV: 'introduce',
      ),
    ),
    (
      'personalSpace',
      'dailyLife',
      'Separate hobbies in a relationship?',
      'İlişkide ayrı hobiler olmalı mı?',
      _c(
        aEn: 'Yes, healthy',
        aTr: 'Evet, sağlıklı',
        aV: 'yes',
        bEn: 'Some shared too',
        bTr: 'Biraz ortak da olsun',
        bV: 'mixed',
        cEn: 'Prefer shared ones',
        cTr: 'Ortak tercih ederim',
        cV: 'shared',
      ),
    ),
    (
      'communication',
      'relationship',
      'After a fight, who should make peace first?',
      'Tartışınca ilk kim barışmalı?',
      _c(
        aEn: 'Whoever cooled down',
        aTr: 'Sakinleşen',
        aV: 'cooled',
        bEn: 'Doesn’t matter who',
        bTr: 'Kim olduğu fark etmez',
        bV: 'anyone',
        cEn: 'The one who started',
        cTr: 'Başlatan',
        cV: 'starter',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Board games with your partner?',
      'Sevgilinle kutu oyunu oynar mısın?',
      _c(
        aEn: 'Competitive yes',
        aTr: 'Rekabetçi evet',
        aV: 'competitive',
        bEn: 'Co-op only',
        bTr: 'Sadece ortak oyun',
        bV: 'coop',
        cEn: 'I’d rather chill',
        cTr: 'Takılmayı tercih ederim',
        cV: 'chill',
      ),
    ),
    (
      'expectations',
      'personality',
      'Big talker or good listener?',
      'Çok konuşan mı, iyi dinleyen mi?',
      _c(
        aEn: 'Talker',
        aTr: 'Konuşkan',
        aV: 'talker',
        bEn: 'Listener',
        bTr: 'Dinleyen',
        bV: 'listener',
        cEn: 'Switch roles',
        cTr: 'Rol değiştiririm',
        cV: 'switch',
      ),
    ),
    (
      'personalSpace',
      'relationship',
      'Is personal space important?',
      'İlişkide kişisel alan önemli mi?',
      _c(
        aEn: 'Very',
        aTr: 'Çok',
        aV: 'very',
        bEn: 'Some is enough',
        bTr: 'Birazı yeter',
        bV: 'some',
        cEn: 'Prefer closeness',
        cTr: 'Yakınlığı tercih ederim',
        cV: 'close',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Concert or cozy café?',
      'Konser mi, sakin kafe mi?',
      _c(
        aEn: 'Concert',
        aTr: 'Konser',
        aV: 'concert',
        bEn: 'Café',
        bTr: 'Kafe',
        bV: 'cafe',
        cEn: 'Both vibes',
        cTr: 'İki ruh hali',
        cV: 'both',
      ),
    ),
    (
      'trust',
      'relationship',
      'Phone passwords between partners?',
      'Sevgililer telefon şifresi paylaşmalı mı?',
      _c(
        aEn: 'Yes, open phones',
        aTr: 'Evet, açık telefon',
        aV: 'yes',
        bEn: 'Only if asked',
        bTr: 'İstenirse',
        bV: 'if_asked',
        cEn: 'No need',
        cTr: 'Gerekmez',
        cV: 'no',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner posts a thirsty compliment under someone’s photo?',
      'Sevgilin birinin fotoğrafına flörtöz yorum atarsa?',
      _c(
        aEn: 'Not cool',
        aTr: 'Hoş değil',
        aV: 'no',
        bEn: 'Depends who',
        bTr: 'Kime olduğuna bağlı',
        bV: 'depends',
        cEn: 'I trust them',
        cTr: 'Güvenirim',
        cV: 'trust',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Early bird workouts or late-night snacks?',
      'Sabah spor mu, gece atıştırma mı?',
      _c(
        aEn: 'Morning workouts',
        aTr: 'Sabah spor',
        aV: 'workout',
        bEn: 'Late snacks',
        bTr: 'Gece atıştırma',
        bV: 'snack',
        cEn: 'Neither regularly',
        cTr: 'Düzenli değil',
        cV: 'neither',
      ),
    ),
    (
      'exes',
      'relationship',
      'Staying friends with an ex?',
      'Eskiyle arkadaş kalmak olur mu?',
      _c(
        aEn: 'Usually no',
        aTr: 'Genelde hayır',
        aV: 'no',
        bEn: 'If truly platonic',
        bTr: 'Gerçekten platonikse',
        bV: 'platonic',
        cEn: 'I’m fine with it',
        cTr: 'Benim için sorun değil',
        cV: 'yes',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner steals the blanket every night?',
      'Sevgilin her gece battaniyeyi çalarsa?',
      _c(
        aEn: 'Second blanket',
        aTr: 'İkinci battaniye',
        aV: 'second',
        bEn: 'Playful tug war',
        bTr: 'Şakacı çekişme',
        bV: 'tug',
        cEn: 'Serious chat',
        cTr: 'Ciddi konuşma',
        cV: 'talk',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Road trip playlist: who DJs?',
      'Yolculuk playlist’ini kim yönetir?',
      _c(
        aEn: 'I DJ',
        aTr: 'Ben yönetirim',
        aV: 'me',
        bEn: 'Take turns',
        bTr: 'Sıra sıra',
        bV: 'turns',
        cEn: 'Shuffle and vibes',
        cTr: 'Karışık ve vibe',
        cV: 'shuffle',
      ),
    ),
    (
      'communication',
      'relationship',
      'Prefer good morning texts?',
      'Günaydın mesajı ister misin?',
      _c(
        aEn: 'Yes, most days',
        aTr: 'Evet, çoğu gün',
        aV: 'yes',
        bEn: 'When we feel it',
        bTr: 'İçimizden gelirse',
        bV: 'natural',
        cEn: 'Not needed',
        cTr: 'Gerekmez',
        cV: 'no',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner picks pineapple on pizza?',
      'Sevgilin pizzaya ananas isterse?',
      _c(
        aEn: 'Respect the choice',
        aTr: 'Seçimine saygı',
        aV: 'respect',
        bEn: 'Half-half peace treaty',
        bTr: 'Yarım yarıma barış',
        bV: 'half',
        cEn: 'Absolute no',
        cTr: 'Kesin hayır',
        cV: 'no',
      ),
    ),
    (
      'expectations',
      'personality',
      'Lead the plan or go with the flow?',
      'Planı sen mi kurarsın, akışa mı bırakırsın?',
      _c(
        aEn: 'I plan',
        aTr: 'Ben planlarım',
        aV: 'plan',
        bEn: 'Go with the flow',
        bTr: 'Akışa bırakırım',
        bV: 'flow',
        cEn: 'We decide together',
        cTr: 'Birlikte karar',
        cV: 'together',
      ),
    ),
    (
      'boundaries',
      'relationship',
      'Posting couple photos: ask first?',
      'Çift fotoğrafı paylaşmadan önce sormalı mı?',
      _c(
        aEn: 'Always ask',
        aTr: 'Her zaman sor',
        aV: 'ask',
        bEn: 'Cute ones are fine',
        bTr: 'Tatlıları olur',
        bV: 'cute_ok',
        cEn: 'I don’t mind',
        cTr: 'Umursamam',
        cV: 'fine',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner is always late?',
      'Sevgilin hep geç kalırsa?',
      _c(
        aEn: 'Annoying',
        aTr: 'Sinir bozucu',
        aV: 'annoying',
        bEn: 'Buffer time forever',
        bTr: 'Hep buffer koyarım',
        bV: 'buffer',
        cEn: 'I adapt',
        cTr: 'Uyuyum sağlarım',
        cV: 'adapt',
      ),
    ),
    (
      'money',
      'lifestyle',
      'Fancy restaurant or street food?',
      'Şık restoran mı, sokak lezzeti mi?',
      _c(
        aEn: 'Fancy spot',
        aTr: 'Şık yer',
        aV: 'fancy',
        bEn: 'Street food',
        bTr: 'Sokak lezzeti',
        bV: 'street',
        cEn: 'Home cooking date',
        cTr: 'Evde yemek randevusu',
        cV: 'home',
      ),
    ),
    (
      'loyalty',
      'relationship',
      'Emotional closeness with someone else?',
      'Başka biriyle duygusal yakınlık sorun mu?',
      _c(
        aEn: 'Yes, serious',
        aTr: 'Evet, ciddi',
        aV: 'serious',
        bEn: 'Depends on boundaries',
        bTr: 'Sınırlara bağlı',
        bV: 'depends',
        cEn: 'Friendship is fine',
        cTr: 'Arkadaşlık olur',
        cV: 'ok',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner laughs at your worst joke?',
      'Sevgilin en kötü şakana gülerse?',
      _c(
        aEn: 'Keep them forever',
        aTr: 'Sonsuza sakla',
        aV: 'keeper',
        bEn: 'Suspect pity laugh',
        bTr: 'Acıma gülüşü şüphesi',
        bV: 'pity',
        cEn: 'I stop joking',
        cTr: 'Şaka yapmayı bırakırım',
        cV: 'stop',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Books or podcasts?',
      'Kitap mı podcast mi?',
      _c(
        aEn: 'Books',
        aTr: 'Kitap',
        aV: 'books',
        bEn: 'Podcasts',
        bTr: 'Podcast',
        bV: 'podcasts',
        cEn: 'Short videos',
        cTr: 'Kısa videolar',
        cV: 'videos',
      ),
    ),
    (
      'socialLife',
      'relationship',
      'Friends night without your partner?',
      'Sevgilisiz arkadaş gecesi olur mu?',
      _c(
        aEn: 'Yes, healthy',
        aTr: 'Evet, sağlıklı',
        aV: 'yes',
        bEn: 'Sometimes',
        bTr: 'Ara sıra',
        bV: 'sometimes',
        cEn: 'Prefer together',
        cTr: 'Birlikte tercih',
        cV: 'together',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Travel: beach resort or city trip?',
      'Tatilde plaj mı, şehir gezisi mi?',
      _c(
        aEn: 'Beach',
        aTr: 'Plaj',
        aV: 'beach',
        bEn: 'City',
        bTr: 'Şehir',
        bV: 'city',
        cEn: 'Nature hike',
        cTr: 'Doğa yürüyüşü',
        cV: 'nature',
      ),
    ),
    (
      'communication',
      'relationship',
      'Bring up small annoyances or let them go?',
      'Küçük rahatsızlıkları söylemek mi, geçmek mi?',
      _c(
        aEn: 'Say it kindly',
        aTr: 'Nazikçe söyle',
        aV: 'say',
        bEn: 'Only if it repeats',
        bTr: 'Tekrarlarsa',
        bV: 'repeats',
        cEn: 'Let most go',
        cTr: 'Çoğunu geç',
        cV: 'let_go',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner sends 40 selfies before a date?',
      'Sevgilin buluşmadan önce 40 selfie atarsa?',
      _c(
        aEn: 'Cute spam',
        aTr: 'Tatlı spam',
        aV: 'cute',
        bEn: 'Pick one together',
        bTr: 'Birini seçelim',
        bV: 'pick',
        cEn: 'Too much',
        cTr: 'Fazla',
        cV: 'too_much',
      ),
    ),
    (
      'expectations',
      'personality',
      'Optimistic or realistic by default?',
      'Varsayılanın iyimser mi, gerçekçi mi?',
      _c(
        aEn: 'Optimistic',
        aTr: 'İyimser',
        aV: 'optimistic',
        bEn: 'Realistic',
        bTr: 'Gerçekçi',
        bV: 'realistic',
        cEn: 'Cautious hopeful',
        cTr: 'Temkinli umutlu',
        cV: 'cautious',
      ),
    ),
    (
      'futurePlans',
      'relationship',
      'Talk about the future early?',
      'Geleceği erken konuşmak ister misin?',
      _c(
        aEn: 'Yes, early clarity',
        aTr: 'Evet, erken netlik',
        aV: 'early',
        bEn: 'When it feels natural',
        bTr: 'Doğal hissettikçe',
        bV: 'natural',
        cEn: 'Later is fine',
        cTr: 'Sonra da olur',
        cV: 'later',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner insists on matching outfits?',
      'Sevgilin kombin kıyafet isterse?',
      _c(
        aEn: 'I’m in',
        aTr: 'Varım',
        aV: 'yes',
        bEn: 'Subtle colors only',
        bTr: 'Sadece uyumlu renk',
        bV: 'subtle',
        cEn: 'Hard pass',
        cTr: 'Hayır teşekkür',
        cV: 'no',
      ),
    ),
    (
      'socialLife',
      'dailyLife',
      'Gym buddy or solo workouts?',
      'Sporu birlikte mi, yalnız mı?',
      _c(
        aEn: 'Together',
        aTr: 'Birlikte',
        aV: 'together',
        bEn: 'Solo',
        bTr: 'Yalnız',
        bV: 'solo',
        cEn: 'Sometimes together',
        cTr: 'Bazen birlikte',
        cV: 'sometimes',
      ),
    ),
    (
      'trust',
      'relationship',
      'Location sharing with your partner?',
      'Sevgilinle konum paylaşımı?',
      _c(
        aEn: 'Comforting',
        aTr: 'Rahatlatıcı',
        aV: 'comfort',
        bEn: 'Only when traveling',
        bTr: 'Sadece yolculukta',
        bV: 'travel',
        cEn: 'Feels like pressure',
        cTr: 'Baskı gibi',
        cV: 'pressure',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner names your plant after an ex as a joke?',
      'Sevgilin bitkiye eski sevgili adı taksa şaka diye?',
      _c(
        aEn: 'Rename immediately',
        aTr: 'Hemen yeniden adlandır',
        aV: 'rename',
        bEn: 'Dark humor ok once',
        bTr: 'Bir kez kara mizah',
        bV: 'once',
        cEn: 'Not funny',
        cTr: 'Komik değil',
        cV: 'no',
      ),
    ),
    (
      'expectations',
      'lifestyle',
      'Live music or studio albums?',
      'Canlı müzik mi, stüdyo albümü mü?',
      _c(
        aEn: 'Live shows',
        aTr: 'Canlı konser',
        aV: 'live',
        bEn: 'Studio albums',
        bTr: 'Stüdyo albüm',
        bV: 'studio',
        cEn: 'Playlists only',
        cTr: 'Sadece playlist',
        cV: 'playlist',
      ),
    ),
    (
      'boundaries',
      'relationship',
      'Checking a partner’s phone?',
      'Partnerinin telefonuna bakmak?',
      _c(
        aEn: 'Not okay',
        aTr: 'Olmaz',
        aV: 'no',
        bEn: 'Only with consent',
        bTr: 'Sadece izniyle',
        bV: 'consent',
        cEn: 'If worried, talk first',
        cTr: 'Endişelenirsem konuş',
        cV: 'talk',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner vs remote control custody?',
      'Kumanda kime kalır?',
      _c(
        aEn: 'Shared democracy',
        aTr: 'Ortak demokrasi',
        aV: 'share',
        bEn: 'Whoever chose the show',
        bTr: 'Diziyi seçen',
        bV: 'chooser',
        cEn: 'I keep it',
        cTr: 'Bende kalır',
        cV: 'me',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Cook together or order in?',
      'Birlikte yemek mi, paket mi?',
      _c(
        aEn: 'Cook together',
        aTr: 'Birlikte pişir',
        aV: 'cook',
        bEn: 'Order in',
        bTr: 'Paket',
        bV: 'order',
        cEn: 'Takeout picnic',
        cTr: 'Paket piknik',
        cV: 'picnic',
      ),
    ),
    (
      'friendship',
      'relationship',
      'Close friend of another gender?',
      'Karşı cinsten çok yakın arkadaş olur mu?',
      _c(
        aEn: 'I’m uncomfortable',
        aTr: 'Rahatsız olurum',
        aV: 'no',
        bEn: 'Boundaries matter',
        bTr: 'Sınırlar önemli',
        bV: 'boundaries',
        cEn: 'Totally fine',
        cTr: 'Tamamen olur',
        cV: 'yes',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner sends voice notes that are 8 minutes?',
      'Sevgilin 8 dakikalık sesli mesaj atarsa?',
      _c(
        aEn: 'I love them',
        aTr: 'Severim',
        aV: 'love',
        bEn: 'Please summarize',
        bTr: 'Özet lütfen',
        bV: 'summary',
        cEn: 'Text me instead',
        cTr: 'Yazı yazsın',
        cV: 'text',
      ),
    ),
    (
      'expectations',
      'personality',
      'Need lots of alone time?',
      'Çok yalnız zamana ihtiyacın var mı?',
      _c(
        aEn: 'Yes, regularly',
        aTr: 'Evet, düzenli',
        aV: 'yes',
        bEn: 'A little',
        bTr: 'Biraz',
        bV: 'little',
        cEn: 'Prefer company',
        cTr: 'Şirketi tercih ederim',
        cV: 'company',
      ),
    ),
    (
      'money',
      'relationship',
      'Split bills or take turns treating?',
      'Hesabı bölüşmek mi, nöbetleşe ısmarlamak mı?',
      _c(
        aEn: 'Split',
        aTr: 'Bölüş',
        aV: 'split',
        bEn: 'Take turns',
        bTr: 'Nöbetleşe',
        bV: 'turns',
        cEn: 'Whoever can',
        cTr: 'Gücü yeten',
        cV: 'ability',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Series binge or one episode rule?',
      'Dizi maratonu mu, bir bölüm kuralı mı?',
      _c(
        aEn: 'Binge',
        aTr: 'Maraton',
        aV: 'binge',
        bEn: 'One episode',
        bTr: 'Bir bölüm',
        bV: 'one',
        cEn: 'Weekend binges only',
        cTr: 'Sadece hafta sonu',
        cV: 'weekend',
      ),
    ),
    (
      'communication',
      'relationship',
      'Prefer talking it out same day?',
      'Aynı gün konuşup bitirmek ister misin?',
      _c(
        aEn: 'Same day',
        aTr: 'Aynı gün',
        aV: 'same_day',
        bEn: 'After cooling down',
        bTr: 'Sakinleşince',
        bV: 'cool_down',
        cEn: 'Depends on the topic',
        cTr: 'Konuya bağlı',
        cV: 'depends',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner puts pineapple AND pickles on pizza?',
      'Sevgilin pizzaya ananas VE turşu koyarsa?',
      _c(
        aEn: 'Chaos accepted',
        aTr: 'Kaos kabul',
        aV: 'chaos',
        bEn: 'Two pizzas solution',
        bTr: 'İki pizza çözümü',
        bV: 'two',
        cEn: 'I order alone',
        cTr: 'Ben ayrı sipariş',
        cV: 'alone',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Alarm: snooze or jump up?',
      'Alarm: ertele mi, hemen kalk mı?',
      _c(
        aEn: 'Snooze forever',
        aTr: 'Ertele sonsuza',
        aV: 'snooze',
        bEn: 'Jump up',
        bTr: 'Hemen kalk',
        bV: 'jump',
        cEn: 'One snooze max',
        cTr: 'En fazla bir erteleme',
        cV: 'one',
      ),
    ),
    (
      'socialLife',
      'relationship',
      'Weekends mostly together?',
      'Hafta sonları çoğunlukla birlikte mi?',
      _c(
        aEn: 'Yes, mostly',
        aTr: 'Evet, çoğunlukla',
        aV: 'yes',
        bEn: 'Mix with friends',
        bTr: 'Arkadaşlarla karışık',
        bV: 'mix',
        cEn: 'Keep independent',
        cTr: 'Bağımsız kalsın',
        cV: 'independent',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner insists on taking 200 photos of you?',
      'Sevgilin senden 200 fotoğraf çekerse?',
      _c(
        aEn: 'Strike a pose',
        aTr: 'Poz veririm',
        aV: 'pose',
        bEn: 'Five photos max',
        bTr: 'En fazla beş',
        bV: 'five',
        cEn: 'Camera ban',
        cTr: 'Kamera yasağı',
        cV: 'ban',
      ),
    ),
    (
      'expectations',
      'personality',
      'Clean-as-you-go or weekend cleanup?',
      'Anında toplamak mı, hafta sonu temizlik mi?',
      _c(
        aEn: 'Clean as I go',
        aTr: 'Anında topla',
        aV: 'asap',
        bEn: 'Weekend reset',
        bTr: 'Hafta sonu reset',
        bV: 'weekend',
        cEn: 'Controlled chaos',
        cTr: 'Kontrollü kaos',
        cV: 'chaos',
      ),
    ),
    (
      'flirting',
      'relationship',
      'Public affection: how much?',
      'Herkese açık sevgi gösterisi ne kadar olsun?',
      _c(
        aEn: 'Hand holding is enough',
        aTr: 'El ele yeter',
        aV: 'hands',
        bEn: 'Hugs and kisses ok',
        bTr: 'Sarılmak öpmek olur',
        bV: 'affection',
        cEn: 'Keep it private',
        cTr: 'Özelde kalsın',
        cV: 'private',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Museum date or amusement park?',
      'Müze mi, lunapark mı?',
      _c(
        aEn: 'Museum',
        aTr: 'Müze',
        aV: 'museum',
        bEn: 'Amusement park',
        bTr: 'Lunapark',
        bV: 'park',
        cEn: 'Park walk + coffee',
        cTr: 'Park + kahve',
        cV: 'walk',
      ),
    ),
    (
      'jealousy',
      'relationship',
      'Partner likes many attractive photos?',
      'Sevgilin çekici fotoğraflara çok beğeni atarsa?',
      _c(
        aEn: 'Bothers me',
        aTr: 'Rahatsız eder',
        aV: 'bothers',
        bEn: 'A few is fine',
        bTr: 'Birkaçı olur',
        bV: 'few',
        cEn: 'I don’t care',
        cTr: 'Umurumda değil',
        cV: 'fine',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner steals your hoodie forever?',
      'Sevgilin sweatshirt’ünü sonsuza çalarsa?',
      _c(
        aEn: 'Cute theft',
        aTr: 'Tatlı hırsızlık',
        aV: 'cute',
        bEn: 'Buy a second one',
        bTr: 'İkinciyi al',
        bV: 'buy',
        cEn: 'I want it back',
        cTr: 'Geri isterim',
        cV: 'back',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Hot weather AC warrior or window breeze?',
      'Sıcakta klima mı, pencere esintisi mi?',
      _c(
        aEn: 'AC full blast',
        aTr: 'Klima full',
        aV: 'ac',
        bEn: 'Open window',
        bTr: 'Pencere',
        bV: 'window',
        cEn: 'Fan middle ground',
        cTr: 'Vantilatör orta yol',
        cV: 'fan',
      ),
    ),
    (
      'loyalty',
      'relationship',
      'Deleting chats before you see them?',
      'Sen görmeden sohbetleri silmek?',
      _c(
        aEn: 'Red flag',
        aTr: 'Kırmızı bayrak',
        aV: 'red',
        bEn: 'Ask why first',
        bTr: 'Önce nedenini sor',
        bV: 'ask',
        cEn: 'Privacy can be ok',
        cTr: 'Mahremiyet olabilir',
        cV: 'privacy',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner claims the aisle seat every flight?',
      'Sevgilin uçakta hep koridor koltuğunu isterse?',
      _c(
        aEn: 'Trade fairly',
        aTr: 'Adil değiş',
        aV: 'trade',
        bEn: 'I take window',
        bTr: 'Ben cam alırım',
        bV: 'window',
        cEn: 'Argue playfully',
        cTr: 'Şakacı tartış',
        cV: 'argue',
      ),
    ),
    (
      'expectations',
      'personality',
      'Need lots of compliments?',
      'Bol iltifat ister misin?',
      _c(
        aEn: 'Yes, often',
        aTr: 'Evet, sık',
        aV: 'often',
        bEn: 'Genuine ones matter',
        bTr: 'Samimi olanlar önemli',
        bV: 'genuine',
        cEn: 'Actions speak louder',
        cTr: 'Davranış yeter',
        cV: 'actions',
      ),
    ),
    (
      'futurePlans',
      'relationship',
      'Meet family early or later?',
      'Aileyle tanışma erken mi geç mi?',
      _c(
        aEn: 'When it’s serious',
        aTr: 'Ciddi olunca',
        aV: 'serious',
        bEn: 'Fairly early',
        bTr: 'Oldukça erken',
        bV: 'early',
        cEn: 'No rush',
        cTr: 'Acelem yok',
        cV: 'later',
      ),
    ),
    (
      'socialLife',
      'lifestyle',
      'Podcast on a date walk?',
      'Yürüyüş randevusunda podcast?',
      _c(
        aEn: 'Yes, shared listen',
        aTr: 'Evet, birlikte dinle',
        aV: 'yes',
        bEn: 'Talk instead',
        bTr: 'Konuşalım',
        bV: 'talk',
        cEn: 'Music only',
        cTr: 'Sadece müzik',
        cV: 'music',
      ),
    ),
    (
      'communication',
      'relationship',
      'Silent treatment during conflict?',
      'Tartışmada sessizlik cezası?',
      _c(
        aEn: 'Not fair',
        aTr: 'Adil değil',
        aV: 'no',
        bEn: 'Short cool-down ok',
        bTr: 'Kısa sakinleşme olur',
        bV: 'short',
        cEn: 'I need space sometimes',
        cTr: 'Bazen alan isterim',
        cV: 'space',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner adds you to a family group chat suddenly?',
      'Sevgilin ani aile grubuna eklerse?',
      _c(
        aEn: 'Wholesome panic',
        aTr: 'Tatlı panik',
        aV: 'panic',
        bEn: 'Ask before adding',
        bTr: 'Eklemeden sor',
        bV: 'ask',
        cEn: 'I’m ready',
        cTr: 'Hazırım',
        cV: 'ready',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Weekday energy: social or recharge?',
      'Hafta içi enerji: sosyal mi, şarj mı?',
      _c(
        aEn: 'Social',
        aTr: 'Sosyal',
        aV: 'social',
        bEn: 'Recharge alone',
        bTr: 'Yalnız şarj',
        bV: 'alone',
        cEn: 'Light hangouts',
        cTr: 'Hafif buluşma',
        cV: 'light',
      ),
    ),
    (
      'friendship',
      'relationship',
      'Partner’s friends dislike you?',
      'Sevgilinin arkadaşları senden hoşlanmazsa?',
      _c(
        aEn: 'It bothers me',
        aTr: 'Rahatsız eder',
        aV: 'bothers',
        bEn: 'Try to connect',
        bTr: 'Bağ kurmaya çalış',
        bV: 'try',
        cEn: 'Partner’s opinion matters more',
        cTr: 'Sevgilinin görüşü önemli',
        cV: 'partner',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner insists on watching reality TV?',
      'Sevgilin reality show dayatırsa?',
      _c(
        aEn: 'I’ll suffer with snacks',
        aTr: 'Atıştırmalıkla katlanırım',
        aV: 'suffer',
        bEn: 'Trade for my show',
        bTr: 'Benim dizimle takas',
        bV: 'trade',
        cEn: 'Separate screens',
        cTr: 'Ayrı ekran',
        cV: 'separate',
      ),
    ),
    (
      'expectations',
      'personality',
      'Risk-taker or safety-first?',
      'Risk alan mı, güvenlikçi mi?',
      _c(
        aEn: 'Risk-taker',
        aTr: 'Risk alan',
        aV: 'risk',
        bEn: 'Safety-first',
        bTr: 'Güvenlik önce',
        bV: 'safe',
        cEn: 'Calculated risks',
        cTr: 'Hesaplı risk',
        cV: 'calculated',
      ),
    ),
    (
      'flirting',
      'relationship',
      'Flirty jokes with strangers while dating?',
      'Flört ederken yabancılarla şakacı flört?',
      _c(
        aEn: 'Not okay',
        aTr: 'Olmaz',
        aV: 'no',
        bEn: 'Light and rare',
        bTr: 'Hafif ve nadir',
        bV: 'light',
        cEn: 'I’m relaxed about it',
        cTr: 'Rahatım',
        cV: 'relaxed',
      ),
    ),
    (
      'money',
      'lifestyle',
      'Dessert first or last?',
      'Tatlı başta mı sonda mı?',
      _c(
        aEn: 'Dessert first',
        aTr: 'Önce tatlı',
        aV: 'first',
        bEn: 'Dessert last',
        bTr: 'Sonda tatlı',
        bV: 'last',
        cEn: 'Skip dessert',
        cTr: 'Tatlıyı geç',
        cV: 'skip',
      ),
    ),
    (
      'personalSpace',
      'relationship',
      'Some evenings completely apart?',
      'Bazı akşamlar tamamen ayrı geçsin mi?',
      _c(
        aEn: 'Yes, healthy',
        aTr: 'Evet, sağlıklı',
        aV: 'yes',
        bEn: 'Rarely',
        bTr: 'Nadiren',
        bV: 'rare',
        cEn: 'Prefer together',
        cTr: 'Birlikte tercih',
        cV: 'together',
      ),
    ),
    (
      'flirting',
      'fun',
      'Partner autotunes your birthday voice note?',
      'Sevgilin doğum günü sesli mesajını autotune’larsa?',
      _c(
        aEn: 'Iconic',
        aTr: 'Efsane',
        aV: 'iconic',
        bEn: 'Cringe but love',
        bTr: 'Utanç ama sevgi',
        bV: 'cringe',
        cEn: 'Please never again',
        cTr: 'Bir daha asla',
        cV: 'never',
      ),
    ),
    (
      'expectations',
      'dailyLife',
      'Rainy day: book or series?',
      'Yağmurlu gün: kitap mı dizi mi?',
      _c(
        aEn: 'Book',
        aTr: 'Kitap',
        aV: 'book',
        bEn: 'Series',
        bTr: 'Dizi',
        bV: 'series',
        cEn: 'Nap and tea',
        cTr: 'Uyku ve çay',
        cV: 'nap',
      ),
    ),
    (
      'communication',
      'relationship',
      'Say “I need time” instead of disappearing?',
      'Kaybolmak yerine “zamana ihtiyacım var” demek?',
      _c(
        aEn: 'Always say it',
        aTr: 'Her zaman söyle',
        aV: 'always',
        bEn: 'When possible',
        bTr: 'Mümkünse',
        bV: 'possible',
        cEn: 'I need quiet first',
        cTr: 'Önce sessizlik isterim',
        cV: 'quiet',
      ),
    ),
    (
      'socialLife',
      'fun',
      'Partner wants matching Halloween costumes?',
      'Sevgilin eşleşen Halloween kostümü isterse?',
      _c(
        aEn: 'Full costume energy',
        aTr: 'Full kostüm enerjisi',
        aV: 'full',
        bEn: 'Subtle theme',
        bTr: 'Hafif tema',
        bV: 'subtle',
        cEn: 'I skip costumes',
        cTr: 'Kostüm geçiyorum',
        cV: 'skip',
      ),
    ),
    (
      'expectations',
      'lifestyle',
      'City weekend or nature escape?',
      'Şehir hafta sonu mu, doğa kaçı mı?',
      _c(
        aEn: 'City',
        aTr: 'Şehir',
        aV: 'city',
        bEn: 'Nature',
        bTr: 'Doğa',
        bV: 'nature',
        cEn: 'Alternate weekends',
        cTr: 'Nöbetleşe hafta sonu',
        cV: 'alternate',
      ),
    ),
  ];

  final out = <_Entry>[];
  for (var i = 0; i < raw.length; i++) {
    final item = raw[i];
    out.add(
      _Entry(
        n: i + 1,
        topic: item.$1,
        category: item.$2,
        en: item.$3,
        tr: item.$4,
        answersExpr: item.$5,
      ),
    );
  }
  return out;
}
